### ISSUE TITLE
What if there is an image in the clipboard?

### ISSUE THREAD

**Issue by xiebruce** [terryyin/clipboard#2]
for example, I copy an image from web, how can I get it with clipboard?
![image](https://user-images.githubusercontent.com/13575500/54662707-ce5d5700-4b19-11e9-892f-29eb1636e3e8.png)

As you can see, I got nothing if there is an image in the clipboard:
![image](https://user-images.githubusercontent.com/13575500/54662863-69eec780-4b1a-11e9-8aee-7050940d62db.png)

**Comment by terryyin** [comment]
This lib is only a redirection to https://github.com/asweigart/pyperclip.

It seems pyperclip can only deal with text content.

On Mac OS paste will give you the url of the image, on Wndows probably gets nothing as you've discovered.

**Comment by xiebruce** [comment]
@terryyin No, macOS give noting too, because I'm using Mac. I use Pillow now, Pillow support image. [Grab Image from Clipboard in Python with Pillow](https://www.devdungeon.com/content/grab-image-clipboard-python-pillow)

**Comment by terryyin** [comment]
Thanks to letting me know the exist of Pillow.
